# HTTP Server (Tomcat) Port
server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    instance:
    preferIpAddress: true
spring:
  application:
    name: TicketRefundService